### ISSUE TITLE
old-stable:  left shift of 1 by 31 places cannot be represented in type 'int'

### ISSUE THREAD

**Issue by matthiaskrgr** [graphitemaster/gmqcc#175]
Tested with  6172ba8
compiled with ```` -fsanitize=address,undefined -g3 -O0 -fno-common -fno-omit-frame-pointer ````

when running the tests, this shows up numerous times ( ````UBSAN_OPTIONS=print_stacktrace=1 make check```` ) :
````
opts.c:173:28: runtime error: left shift of 1 by 31 places cannot be represented in type 'int'
    #0 0x4ff137 in opts_set /home/matthias/vcs/github/gmqcc/opts.c:173:28
    #1 0x500683 in opts_setdefault /home/matthias/vcs/github/gmqcc/opts.c:91:5
    #2 0x4ffbe7 in opts_init /home/matthias/vcs/github/gmqcc/opts.c:130:5
    #3 0x512f41 in main /home/matthias/vcs/github/gmqcc/main.c:568:5
    #4 0x7f9071d3b400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289
    #5 0x41a659 in _start (/home/matthias/vcs/github/gmqcc/gmqcc+0x41a659)
````

**Comment by matthiaskrgr** [comment]
Fixed, at least in old-stable branch.
