### ISSUE TITLE
UB and leaks in master branch

### ISSUE THREAD

**Issue by matthiaskrgr** [graphitemaster/gmqcc#176]
compile with ````-fsanitize=address,undefined -g3 -O0 -fno-common -fno-omit-frame-pointer````, add ````-fsanitize=address,undefined```` to LDFLAGS, compile and run tests via ````UBSAN_OPTIONS=print_stacktrace=1 make test````

leak in the testrunner itself:
````
=================================================================
==28148==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4368 byte(s) in 69 object(s) allocated from:
    #0 0x4e784b in operator new(unsigned long) /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:78:35
    #1 0x524679 in __gnu_cxx::new_allocator<char*>::allocate(unsigned long, void const*) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/ext/new_allocator.h:104:27
    #2 0x5245c3 in std::allocator_traits<std::allocator<char*> >::allocate(std::allocator<char*>&, unsigned long) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/bits/alloc_traits.h:416:20
    #3 0x5237b6 in std::_Vector_base<char*, std::allocator<char*> >::_M_allocate(unsigned long) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/bits/stl_vector.h:170:20
    #4 0x526a9b in void std::vector<char*, std::allocator<char*> >::_M_emplace_back_aux<char*>(char*&&) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/bits/vector.tcc:412:28
    #5 0x5266d7 in void std::vector<char*, std::allocator<char*> >::emplace_back<char*>(char*&&) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/bits/vector.tcc:101:4
    #6 0x525e7f in std::vector<char*, std::allocator<char*> >::push_back(char*&&) /usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/bits/stl_vector.h:933:9
    #7 0x519fff in task_template_parse(char const*, task_template_t*, _IO_FILE*, unsigned long*) /home/matthias/vcs/github/gmqcc/test.cpp:369:36
    #8 0x514903 in task_template_compile(char const*, char const*, unsigned long*) /home/matthias/vcs/github/gmqcc/test.cpp:448:10
    #9 0x5080d0 in task_propagate(char const*, unsigned long*, char const*) /home/matthias/vcs/github/gmqcc/test.cpp:636:41
    #10 0x5066ff in test_perform(char const*, char const*) /home/matthias/vcs/github/gmqcc/test.cpp:1221:10
    #11 0x505d3c in main /home/matthias/vcs/github/gmqcc/test.cpp:1302:15
    #12 0x7f167b646400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Direct leak of 2640 byte(s) in 55 object(s) allocated from:
    #0 0x4b98fc in malloc /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64:3
    #1 0x51623b in task_popen(char const*, char const*) /home/matthias/vcs/github/gmqcc/test.cpp:35:31
    #2 0x50a4c1 in task_propagate(char const*, unsigned long*, char const*) /home/matthias/vcs/github/gmqcc/test.cpp:740:41
    #3 0x5066ff in test_perform(char const*, char const*) /home/matthias/vcs/github/gmqcc/test.cpp:1221:10
    #4 0x505d3c in main /home/matthias/vcs/github/gmqcc/test.cpp:1302:15
    #5 0x7f167b646400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

SUMMARY: AddressSanitizer: 7008 byte(s) leaked in 124 allocation(s).
Makefile:86: recipe for target 'test' failed
make: *** [test] Error 1
````

this is just the findings in the first error output file TMPDAT.accumulate.tmpl.dat.stderr
````
stat.cpp:212:17: runtime error: call to function ppmacro_delete(ppmacro*) through pointer to incorrect function type 'void (*)(void *)'
/home/matthias/vcs/github/gmqcc/ftepp.cpp:247: note: ppmacro_delete(ppmacro*) defined here
    #0 0x95ebf3 in util_htrem(hash_table_s*, void (*)(void*)) /home/matthias/vcs/github/gmqcc/stat.cpp:212:17
    #1 0x63c7d9 in ftepp_delete(ftepp_t*) /home/matthias/vcs/github/gmqcc/ftepp.cpp:287:5
    #2 0x63c1d0 in ftepp_finish(ftepp_t*) /home/matthias/vcs/github/gmqcc/ftepp.cpp:1946:5
    #3 0x80ba42 in main /home/matthias/vcs/github/gmqcc/main.cpp:721:9
    #4 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289
    #5 0x41b739 in _start (/home/matthias/vcs/github/gmqcc/gmqcc+0x41b739)

SUMMARY: AddressSanitizer: undefined-behavior stat.cpp:212:17 in 

=================================================================
==28251==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3952 byte(s) in 13 object(s) allocated from:
    #0 0x4e851b in operator new(unsigned long) /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:78:35
    #1 0x5dc248 in fold::constgen_float(float, bool) /home/matthias/vcs/github/gmqcc/fold.cpp:963:23
    #2 0x8d9efa in parse_sya_operand(parser_t*, shunt*, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1576:46
    #3 0x8876d1 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1917:18
    #4 0x8573de in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/github/gmqcc/parser.cpp:5648:38
    #5 0x842d52 in parser_global_statement(parser_t*) /home/matthias/vcs/github/gmqcc/parser.cpp:5906:16
    #6 0x83145b in parser_compile(parser_t*) /home/matthias/vcs/github/gmqcc/parser.cpp:6097:18
    #7 0x831d6a in parser_compile_string(parser_t*, char const*, char const*, unsigned long) /home/matthias/vcs/github/gmqcc/parser.cpp:6137:12
    #8 0x80b6b2 in main /home/matthias/vcs/github/gmqcc/main.cpp:700:30
    #9 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Direct leak of 304 byte(s) in 1 object(s) allocated from:
    #0 0x4e851b in operator new(unsigned long) /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:78:35
    #1 0x5dd980 in fold::constgen_vector(vec3_t) /home/matthias/vcs/github/gmqcc/fold.cpp:979:22
    #2 0x5db786 in fold::fold(parser_t*) /home/matthias/vcs/github/gmqcc/fold.cpp:926:5
    #3 0x830ae1 in parser_create() /home/matthias/vcs/github/gmqcc/parser.cpp:6083:22
    #4 0x8080ba in main /home/matthias/vcs/github/gmqcc/main.cpp:598:24
    #5 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Direct leak of 304 byte(s) in 1 object(s) allocated from:
    #0 0x4e851b in operator new(unsigned long) /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:78:35
    #1 0x5dd980 in fold::constgen_vector(vec3_t) /home/matthias/vcs/github/gmqcc/fold.cpp:979:22
    #2 0x5db983 in fold::fold(parser_t*) /home/matthias/vcs/github/gmqcc/fold.cpp:927:5
    #3 0x830ae1 in parser_create() /home/matthias/vcs/github/gmqcc/parser.cpp:6083:22
    #4 0x8080ba in main /home/matthias/vcs/github/gmqcc/main.cpp:598:24
    #5 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Direct leak of 304 byte(s) in 1 object(s) allocated from:
    #0 0x4e851b in operator new(unsigned long) /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:78:35
    #1 0x5dc248 in fold::constgen_float(float, bool) /home/matthias/vcs/github/gmqcc/fold.cpp:963:23
    #2 0x5db543 in fold::fold(parser_t*) /home/matthias/vcs/github/gmqcc/fold.cpp:924:5
    #3 0x830ae1 in parser_create() /home/matthias/vcs/github/gmqcc/parser.cpp:6083:22
    #4 0x8080ba in main /home/matthias/vcs/github/gmqcc/main.cpp:598:24
    #5 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Direct leak of 304 byte(s) in 1 object(s) allocated from:
    #0 0x4e851b in operator new(unsigned long) /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:78:35
    #1 0x5dc248 in fold::constgen_float(float, bool) /home/matthias/vcs/github/gmqcc/fold.cpp:963:23
    #2 0x5db4d5 in fold::fold(parser_t*) /home/matthias/vcs/github/gmqcc/fold.cpp:923:5
    #3 0x830ae1 in parser_create() /home/matthias/vcs/github/gmqcc/parser.cpp:6083:22
    #4 0x8080ba in main /home/matthias/vcs/github/gmqcc/main.cpp:598:24
    #5 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Direct leak of 304 byte(s) in 1 object(s) allocated from:
    #0 0x4e851b in operator new(unsigned long) /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:78:35
    #1 0x5dc248 in fold::constgen_float(float, bool) /home/matthias/vcs/github/gmqcc/fold.cpp:963:23
    #2 0x5db3f9 in fold::fold(parser_t*) /home/matthias/vcs/github/gmqcc/fold.cpp:921:5
    #3 0x830ae1 in parser_create() /home/matthias/vcs/github/gmqcc/parser.cpp:6083:22
    #4 0x8080ba in main /home/matthias/vcs/github/gmqcc/main.cpp:598:24
    #5 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Direct leak of 304 byte(s) in 1 object(s) allocated from:
    #0 0x4e851b in operator new(unsigned long) /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:78:35
    #1 0x5dc248 in fold::constgen_float(float, bool) /home/matthias/vcs/github/gmqcc/fold.cpp:963:23
    #2 0x5db467 in fold::fold(parser_t*) /home/matthias/vcs/github/gmqcc/fold.cpp:922:5
    #3 0x830ae1 in parser_create() /home/matthias/vcs/github/gmqcc/parser.cpp:6083:22
    #4 0x8080ba in main /home/matthias/vcs/github/gmqcc/main.cpp:598:24
    #5 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4ba5cc in malloc /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64:3
    #1 0x95bec3 in util_htnew(unsigned long) /home/matthias/vcs/github/gmqcc/stat.cpp:99:38
    #2 0x5db2a7 in fold::fold(parser_t*) /home/matthias/vcs/github/gmqcc/fold.cpp:919:32
    #3 0x830ae1 in parser_create() /home/matthias/vcs/github/gmqcc/parser.cpp:6083:22
    #4 0x8080ba in main /home/matthias/vcs/github/gmqcc/main.cpp:598:24
    #5 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4ba5cc in malloc /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64:3
    #1 0x95bec3 in util_htnew(unsigned long) /home/matthias/vcs/github/gmqcc/stat.cpp:99:38
    #2 0x5db1ad in fold::fold(parser_t*) /home/matthias/vcs/github/gmqcc/fold.cpp:918:32
    #3 0x830ae1 in parser_create() /home/matthias/vcs/github/gmqcc/parser.cpp:6083:22
    #4 0x8080ba in main /home/matthias/vcs/github/gmqcc/main.cpp:598:24
    #5 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Indirect leak of 8192 byte(s) in 1 object(s) allocated from:
    #0 0x4ba5cc in malloc /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64:3
    #1 0x95beee in util_htnew(unsigned long) /home/matthias/vcs/github/gmqcc/stat.cpp:102:45
    #2 0x5db2a7 in fold::fold(parser_t*) /home/matthias/vcs/github/gmqcc/fold.cpp:919:32
    #3 0x830ae1 in parser_create() /home/matthias/vcs/github/gmqcc/parser.cpp:6083:22
    #4 0x8080ba in main /home/matthias/vcs/github/gmqcc/main.cpp:598:24
    #5 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Indirect leak of 8192 byte(s) in 1 object(s) allocated from:
    #0 0x4ba5cc in malloc /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64:3
    #1 0x95beee in util_htnew(unsigned long) /home/matthias/vcs/github/gmqcc/stat.cpp:102:45
    #2 0x5db1ad in fold::fold(parser_t*) /home/matthias/vcs/github/gmqcc/fold.cpp:918:32
    #3 0x830ae1 in parser_create() /home/matthias/vcs/github/gmqcc/parser.cpp:6083:22
    #4 0x8080ba in main /home/matthias/vcs/github/gmqcc/main.cpp:598:24
    #5 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Indirect leak of 912 byte(s) in 3 object(s) allocated from:
    #0 0x4e851b in operator new(unsigned long) /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:78:35
    #1 0x5e0db5 in fold::constgen_string(char const*, bool) /home/matthias/vcs/github/gmqcc/fold.cpp:1003:15
    #2 0x8da63f in parse_sya_operand(parser_t*, shunt*, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1583:46
    #3 0x8876d1 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1917:18
    #4 0x9076d7 in parse_expression(parser_t*, bool, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1982:25
    #5 0x8f9400 in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:3609:31
    #6 0x8f05d4 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/github/gmqcc/parser.cpp:3774:14
    #7 0x897c76 in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/github/gmqcc/parser.cpp:4163:10
    #8 0x85ab26 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/github/gmqcc/parser.cpp:5737:18
    #9 0x843089 in parser_global_statement(parser_t*) /home/matthias/vcs/github/gmqcc/parser.cpp:5912:16
    #10 0x83145b in parser_compile(parser_t*) /home/matthias/vcs/github/gmqcc/parser.cpp:6097:18
    #11 0x831d6a in parser_compile_string(parser_t*, char const*, char const*, unsigned long) /home/matthias/vcs/github/gmqcc/parser.cpp:6137:12
    #12 0x80b6b2 in main /home/matthias/vcs/github/gmqcc/main.cpp:700:30
    #13 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Indirect leak of 72 byte(s) in 3 object(s) allocated from:
    #0 0x4ba5cc in malloc /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64:3
    #1 0x95d11a in _util_htnewpair(char const*, void*) /home/matthias/vcs/github/gmqcc/stat.cpp:72:32
    #2 0x95c9ab in util_htseth(hash_table_s*, char const*, unsigned long, void*) /home/matthias/vcs/github/gmqcc/stat.cpp:128:19
    #3 0x5e1746 in fold::constgen_string(char const*, bool) /home/matthias/vcs/github/gmqcc/fold.cpp:1012:5
    #4 0x8da63f in parse_sya_operand(parser_t*, shunt*, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1583:46
    #5 0x8876d1 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1917:18
    #6 0x9076d7 in parse_expression(parser_t*, bool, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1982:25
    #7 0x8f9400 in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:3609:31
    #8 0x8f05d4 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/github/gmqcc/parser.cpp:3774:14
    #9 0x897c76 in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/github/gmqcc/parser.cpp:4163:10
    #10 0x85ab26 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/github/gmqcc/parser.cpp:5737:18
    #11 0x843089 in parser_global_statement(parser_t*) /home/matthias/vcs/github/gmqcc/parser.cpp:5912:16
    #12 0x83145b in parser_compile(parser_t*) /home/matthias/vcs/github/gmqcc/parser.cpp:6097:18
    #13 0x831d6a in parser_compile_string(parser_t*, char const*, char const*, unsigned long) /home/matthias/vcs/github/gmqcc/parser.cpp:6137:12
    #14 0x80b6b2 in main /home/matthias/vcs/github/gmqcc/main.cpp:700:30
    #15 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Indirect leak of 28 byte(s) in 3 object(s) allocated from:
    #0 0x4ba5cc in malloc /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64:3
    #1 0x95b75f in stat_mem_strdup(char const*, bool) /home/matthias/vcs/github/gmqcc/stat.cpp:19:48
    #2 0x82af30 in parser_strdup(char const*) /home/matthias/vcs/github/gmqcc/parser.cpp:88:12
    #3 0x5e1481 in fold::constgen_string(char const*, bool) /home/matthias/vcs/github/gmqcc/fold.cpp:1009:31
    #4 0x8da63f in parse_sya_operand(parser_t*, shunt*, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1583:46
    #5 0x8876d1 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1917:18
    #6 0x9076d7 in parse_expression(parser_t*, bool, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1982:25
    #7 0x8f9400 in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:3609:31
    #8 0x8f05d4 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/github/gmqcc/parser.cpp:3774:14
    #9 0x897c76 in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/github/gmqcc/parser.cpp:4163:10
    #10 0x85ab26 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/github/gmqcc/parser.cpp:5737:18
    #11 0x843089 in parser_global_statement(parser_t*) /home/matthias/vcs/github/gmqcc/parser.cpp:5912:16
    #12 0x83145b in parser_compile(parser_t*) /home/matthias/vcs/github/gmqcc/parser.cpp:6097:18
    #13 0x831d6a in parser_compile_string(parser_t*, char const*, char const*, unsigned long) /home/matthias/vcs/github/gmqcc/parser.cpp:6137:12
    #14 0x80b6b2 in main /home/matthias/vcs/github/gmqcc/main.cpp:700:30
    #15 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

Indirect leak of 28 byte(s) in 3 object(s) allocated from:
    #0 0x4ba5cc in malloc /home/matthias/LLVM/LLVM_3_9/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64:3
    #1 0x95b75f in stat_mem_strdup(char const*, bool) /home/matthias/vcs/github/gmqcc/stat.cpp:19:48
    #2 0x95d143 in _util_htnewpair(char const*, void*) /home/matthias/vcs/github/gmqcc/stat.cpp:75:23
    #3 0x95c9ab in util_htseth(hash_table_s*, char const*, unsigned long, void*) /home/matthias/vcs/github/gmqcc/stat.cpp:128:19
    #4 0x5e1746 in fold::constgen_string(char const*, bool) /home/matthias/vcs/github/gmqcc/fold.cpp:1012:5
    #5 0x8da63f in parse_sya_operand(parser_t*, shunt*, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1583:46
    #6 0x8876d1 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1917:18
    #7 0x9076d7 in parse_expression(parser_t*, bool, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:1982:25
    #8 0x8f9400 in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/github/gmqcc/parser.cpp:3609:31
    #9 0x8f05d4 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/github/gmqcc/parser.cpp:3774:14
    #10 0x897c76 in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/github/gmqcc/parser.cpp:4163:10
    #11 0x85ab26 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/github/gmqcc/parser.cpp:5737:18
    #12 0x843089 in parser_global_statement(parser_t*) /home/matthias/vcs/github/gmqcc/parser.cpp:5912:16
    #13 0x83145b in parser_compile(parser_t*) /home/matthias/vcs/github/gmqcc/parser.cpp:6097:18
    #14 0x831d6a in parser_compile_string(parser_t*, char const*, char const*, unsigned long) /home/matthias/vcs/github/gmqcc/parser.cpp:6137:12
    #15 0x80b6b2 in main /home/matthias/vcs/github/gmqcc/main.cpp:700:30
    #16 0x7f4250393400 in __libc_start_main /usr/src/debug/glibc-2.24-33-ge9e69e4/csu/../csu/libc-start.c:289

SUMMARY: AddressSanitizer: 23232 byte(s) leaked in 35 allocation(s).
`````
I did not add all the logs because
````
cat *stderr | wc -l 
12690
````

**Comment by graphitemaster** [comment]
these need to be rerun
