### ISSUE TITLE
crash compiling xonotic code

### ISSUE THREAD

**Issue by matthiaskrgr** [graphitemaster/gmqcc#178]
reported by kyrios via irc in #xonotic

xonotic data repo @ c4e0c3f1fa4102e0661ac0f6df10e28159bea595
xonotic gmqcc repo @ 163c4b99a4bef8746fc9d3caa8dc6c54c11d4955

compile gmqcc in the mirror repo with gcc -fsanitize=address,undefined
make clean  inside  data/xonotic-data.pk3dir/
./all compile
=>
````
+ err=0
+ set -e
+ '[' 0 -ne 0 ']'
+ sed 's/^#\(line\)\? \([[:digit:]]\+\) "\(.*\)".*/\n#pragma file(\3)\n#pragma line(\2)/g' ../.tmp/menu.txt
+ qcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.dat ../../.tmp/menu.qc
++ basename ../../../../gmqcc/gmqcc
+ echo + gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.dat ../../.tmp/menu.qc
+ gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.dat ../../.tmp/menu.qc
+ cd tools
+ ../../../../gmqcc/gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.dat ../../.tmp/menu.qc
fold.h:17:8: runtime error: load of value 160, which is not a valid value for type 'bool'
Mode: manual
There are 1 items to compile:
  item: ../../.tmp/menu.qc (qc)
fold.cpp:1385:41: runtime error: downcast of address 0x60e00000d940 which does not point to an object of type 'ast_value'
0x60e00000d940: note: object is of type 'ast_call'
 03 00 00 00  d0 ea 62 00 00 00 00 00  90 24 00 00 20 60 00 00  1b 00 00 00 00 00 00 00  14 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'ast_call'
parser.cpp:2101:25: runtime error: downcast of address 0x60e00000d780 which does not point to an object of type 'ast_unary'
0x60e00000d780: note: object is of type 'ast_call'
 03 00 00 00  d0 ea 62 00 00 00 00 00  40 95 01 00 30 60 00 00  09 00 00 00 00 00 00 00  07 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'ast_call'
fold.cpp:1387:41: runtime error: downcast of address 0x7f3f124ec5e0 which does not point to an object of type 'ast_value'
0x7f3f124ec5e0: note: object has invalid vptr
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
fold.cpp:1386:41: runtime error: downcast of address 0x60e00000d400 which does not point to an object of type 'ast_value'
0x60e00000d400: note: object is of type 'ast_call'
 03 00 00 00  d0 ea 62 00 00 00 00 00  40 95 01 00 30 60 00 00  13 00 00 00 00 00 00 00  16 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'ast_call'
fold.cpp:1387:41: runtime error: member access within misaligned address 0x00000000000e for type 'struct ast_value', which requires 8 byte alignment
0x00000000000e: note: pointer points here
<memory cannot be printed>
ASAN:DEADLYSIGNAL
=================================================================
==7222==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000000e (pc 0x0000004a2e58 bp 0x0fffc07d00d2 sp 0x7ffe03e80630 T0)
    #0 0x4a2e57 in fold::op(oper_info const*, ast_expression**) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x4a2e57)
    #1 0x58f60e in parser_sy_apply_operator(parser_t*, shunt*) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x58f60e)
    #2 0x5a08b3 in parser_close_paren(parser_t*, shunt*) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x5a08b3)
    #3 0x5a455b in parse_expression_leave(parser_t*, bool, bool, bool) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x5a455b)
    #4 0x5aeaa5 in parse_expression(parser_t*, bool, bool) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x5aeaa5)
    #5 0x5b0cfd in parse_return(parser_t*, ast_block*, ast_expression**) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x5b0cfd)
    #6 0x5b8b22 in parse_statement(parser_t*, ast_block*, ast_expression**, bool) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x5b8b22)
    #7 0x5ba6fe in parse_block_into(parser_t*, ast_block*) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x5ba6fe)
    #8 0x5c19b5 in parse_function_body(parser_t*, ast_value*) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x5c19b5)
    #9 0x5ceb99 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x5ceb99)
    #10 0x5d259c in parser_global_statement(parser_t*) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x5d259c)
    #11 0x5d2e18 in parser_compile(parser_t*) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x5d2e18)
    #12 0x5d30aa in parser_compile_file(parser_t*, char const*) (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x5d30aa)
    #13 0x55ac1a in main (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x55ac1a)
    #14 0x7f3f103e5400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #15 0x402d49 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x402d49)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x4a2e57) in fold::op(oper_info const*, ast_expression**)
==7222==ABORTING
Makefile:120: recipe for target '../menu.dat' failed
make[1]: *** [../menu.dat] Error 1
make[1]: *** Waiting for unfinished jobs....
````

**Comment by matthiaskrgr** [comment]
Looks like the crashes are gone, but UB remains (clang compiler-rt:)
````
+ err=0
+ set -e
+ '[' 0 -ne 0 ']'
+ sed 's/^#\(line\)\? \([[:digit:]]\+\) "\(.*\)".*/\n#pragma file(\3)\n#pragma line(\2)/g' ../.tmp/server.txt
+ qcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../progs.dat ../../.tmp/server.qc
++ basename ../../../../gmqcc/gmqcc
+ echo + gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../progs.dat ../../.tmp/server.qc
+ gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../progs.dat ../../.tmp/server.qc
+ cd tools
+ ../../../../gmqcc/gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../progs.dat ../../.tmp/server.qc
Mode: manual
There are 1 items to compile:
  item: ../../.tmp/server.qc (qc)
fold.cpp:1387:20: runtime error: downcast of misaligned address 0x000008000003 for type 'ast_value', which requires 8 byte alignment
0x000008000003: note: pointer points here
<memory cannot be printed>
    #0 0x62614d in fold::op(oper_info const*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/fold.cpp:1387:20
    #1 0x8b4891 in parser_sy_apply_operator(parser_t*, shunt*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:886:40
    #2 0x8d288f in parser_close_paren(parser_t*, shunt*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1421:14
    #3 0x883c0c in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1883:22
    #4 0x8fe197 in parse_expression(parser_t*, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1985:25
    #5 0x8f2da3 in parse_return(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:2663:15
    #6 0x8ebf64 in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3492:20
    #7 0x90b072 in parse_switch_go(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3225:18
    #8 0x8fc0c8 in parse_switch(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3016:10
    #9 0x8ed3b8 in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3524:20
    #10 0x8e9164 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3768:14
    #11 0x894522 in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:4157:10
    #12 0x8595b1 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5731:18
    #13 0x8426d9 in parser_global_statement(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5906:16
    #14 0x83578b in parser_compile(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6108:18
    #15 0x835376 in parser_compile_file(parser_t*, char const*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6138:12
    #16 0x80debb in main /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:709:26
    #17 0x7f3d707f4400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #18 0x41bf09 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x41bf09)

SUMMARY: AddressSanitizer: undefined-behavior fold.cpp:1387:20 in 
fold.cpp:1386:20: runtime error: downcast of misaligned address 0x00000098ab26 for type 'ast_value', which requires 8 byte alignment
0x00000098ab26: note: pointer points here
 74 6d 70 00 33 20  33 32 20 38 20 37 20 5f  5f 62 65 67 69 6e 20 36  34 20 38 20 35 20 5f 5f  65 6e
             ^ 
    #0 0x626054 in fold::op(oper_info const*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/fold.cpp:1386:20
    #1 0x89f8da in parser_sy_apply_operator(parser_t*, shunt*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:485:40
    #2 0x885d63 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1960:14
    #3 0x8f4642 in parse_if(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:2150:12
    #4 0x8ec20e in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3496:20
    #5 0x8e9164 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3768:14
    #6 0x894522 in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:4157:10
    #7 0x8595b1 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5731:18
    #8 0x8423a2 in parser_global_statement(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5900:16
    #9 0x83578b in parser_compile(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6108:18
    #10 0x835376 in parser_compile_file(parser_t*, char const*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6138:12
    #11 0x80debb in main /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:709:26
    #12 0x7f3d707f4400 in __libc_start_main (/lib64/libc.so.6+0x20400)
    #13 0x41bf09 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x41bf09)

SUMMARY: AddressSanitizer: undefined-behavior fold.cpp:1386:20 in 
writing '/home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.dat' and '/home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.lno'...
````

**Comment by graphitemaster** [comment]
these need to be rerun
