### ISSUE TITLE
UB when compiling xonotic qc sources

### ISSUE THREAD

**Issue by matthiaskrgr** [graphitemaster/gmqcc#182]
````
ake[1]: Entering directory '/home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc'
make[1]: Entering directory `/home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/client'
./tools/qcc.sh client ../csprogs.dat client/progs.inc
make[1]: Entering directory `/home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/menu'
+ qpp client/progs.inc ../csprogs.dat -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0
+ IN=client/progs.inc
+ OUT=../csprogs.dat
+ case ${MODE} in
+ DEFS='-DGAMEQC -DCSQC'
+ echo + cc -xc -E -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DGAMEQC -DCSQC client/progs.inc
+ cc -xc -E -I. -DGMQCC -DXONOTIC=1 -DWATERMARK="xonotic-v0.8.2-865-gbf48359" -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DGAMEQC -DCSQC client/progs.inc
+ set +e
+ cc -xc -E -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DGAMEQC -DCSQC -dM -H client/progs.inc
+ cc -xc -E -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DGAMEQC -DCSQC -MMD -MP -MT ../csprogs.dat -Wall -Wundef -Werror client/progs.inc -o ../.tmp/client.txt
./tools/qcc.sh menu ../menu.dat menu/progs.inc
make[1]: Entering directory `/home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/server'
./tools/qcc.sh server ../progs.dat server/progs.inc
+ qpp server/progs.inc ../progs.dat -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0
+ IN=server/progs.inc
+ OUT=../progs.dat
+ case ${MODE} in
+ DEFS='-DGAMEQC -DSVQC'
+ echo + cc -xc -E -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DGAMEQC -DSVQC server/progs.inc
+ cc -xc -E -I. -DGMQCC -DXONOTIC=1 -DWATERMARK="xonotic-v0.8.2-865-gbf48359" -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DGAMEQC -DSVQC server/progs.inc
+ set +e
+ cc -xc -E -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DGAMEQC -DSVQC -dM -H server/progs.inc
+ qpp menu/progs.inc ../menu.dat -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0
+ IN=menu/progs.inc
+ OUT=../menu.dat
+ case ${MODE} in
+ DEFS=-DMENUQC
+ echo + cc -xc -E -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DMENUQC menu/progs.inc
+ cc -xc -E -I. -DGMQCC -DXONOTIC=1 -DWATERMARK="xonotic-v0.8.2-865-gbf48359" -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DMENUQC menu/progs.inc
+ set +e
+ cc -xc -E -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DMENUQC -dM -H menu/progs.inc
+ cc -xc -E -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DMENUQC -MMD -MP -MT ../menu.dat -Wall -Wundef -Werror menu/progs.inc -o ../.tmp/menu.txt
+ cc -xc -E -I. -DGMQCC -DXONOTIC=1 '-DWATERMARK="xonotic-v0.8.2-865-gbf48359"' -DNDEBUG=1 -DENABLE_EFFECTINFO=0 -DENABLE_DEBUGDRAW=0 -DENABLE_DEBUGTRACE=0 -DGAMEQC -DSVQC -MMD -MP -MT ../progs.dat -Wall -Wundef -Werror server/progs.inc -o ../.tmp/server.txt
+ err=0
+ set -e
+ '[' 0 -ne 0 ']'
+ sed 's/^#\(line\)\? \([[:digit:]]\+\) "\(.*\)".*/\n#pragma file(\3)\n#pragma line(\2)/g' ../.tmp/menu.txt
+ qcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.dat ../../.tmp/menu.qc
++ basename ../../../../gmqcc/gmqcc
+ echo + gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.dat ../../.tmp/menu.qc
+ gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.dat ../../.tmp/menu.qc
+ cd tools
+ ../../../../gmqcc/gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.dat ../../.tmp/menu.qc
stat.cpp:31:19: runtime error: pointer index expression with base 0x000000000000 overflowed to 0xfffffffffffffff0
    #0 0x87bd41 in _util_vec_grow(void**, unsigned long, unsigned long) /home/matthias/vcs/git/xonotic/gmqcc/stat.cpp:31:19
    #1 0x765a9d in options_parse(int, char**) /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:484:13
    #2 0x75522b in main /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:532:10
    #3 0x7f3421c68430 in __libc_start_main (/lib64/libc.so.6+0x20430)
    #4 0x41bef9 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x41bef9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior stat.cpp:31:19 in 
Mode: manual
There are 1 items to compile:
  item: ../../.tmp/menu.qc (qc)
fold.cpp:1386:20: runtime error: downcast of misaligned address 0x0000004a6b45 for type 'ast_value', which requires 8 byte alignment
0x0000004a6b45: note: pointer points here
 2b 50 7d 00 48 81 c4  38 08 00 00 5b 41 5c 41  5d 41 5e 41 5f 5d c3 4c  89 ff 4c 89 f6 4c 89 e2  48
             ^ 
    #0 0x5d3926 in fold::op(oper_info const*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/fold.cpp:1386:20
    #1 0x7dd4ba in parser_sy_apply_operator(parser_t*, shunt*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:511:40
    #2 0x7c6d48 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1959:14
    #3 0x82cc57 in parse_expression(parser_t*, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1984:25
    #4 0x822fec in parse_return(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:2662:15
    #5 0x81d17e in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3492:20
    #6 0x81a7a5 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3768:14
    #7 0x7d33ba in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:4157:10
    #8 0x7a09d7 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5731:18
    #9 0x78c6d1 in parser_global_statement(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5900:16
    #10 0x781cbd in parser_compile(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6108:18
    #11 0x781945 in parser_compile_file(parser_t*, char const*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6138:12
    #12 0x75b09b in main /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:709:26
    #13 0x7f3421c68430 in __libc_start_main (/lib64/libc.so.6+0x20430)
    #14 0x41bef9 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x41bef9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior fold.cpp:1386:20 in 
fold.cpp:1387:20: runtime error: downcast of misaligned address 0x000000000006 for type 'ast_value', which requires 8 byte alignment
0x000000000006: note: pointer points here
<memory cannot be printed>
    #0 0x5d3a44 in fold::op(oper_info const*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/fold.cpp:1387:20
    #1 0x7f09d0 in parser_sy_apply_operator(parser_t*, shunt*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:912:40
    #2 0x8077dd in parser_close_paren(parser_t*, shunt*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1420:14
    #3 0x7c50d4 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1882:22
    #4 0x82cc57 in parse_expression(parser_t*, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1984:25
    #5 0x822fec in parse_return(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:2662:15
    #6 0x81d17e in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3492:20
    #7 0x81a7a5 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3768:14
    #8 0x7d33ba in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:4157:10
    #9 0x7a09d7 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5731:18
    #10 0x78c6d1 in parser_global_statement(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5900:16
    #11 0x781cbd in parser_compile(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6108:18
    #12 0x781945 in parser_compile_file(parser_t*, char const*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6138:12
    #13 0x75b09b in main /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:709:26
    #14 0x7f3421c68430 in __libc_start_main (/lib64/libc.so.6+0x20430)
    #15 0x41bef9 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x41bef9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior fold.cpp:1387:20 in 
+ err=0
+ set -e
+ '[' 0 -ne 0 ']'
+ sed 's/^#\(line\)\? \([[:digit:]]\+\) "\(.*\)".*/\n#pragma file(\3)\n#pragma line(\2)/g' ../.tmp/client.txt
+ qcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../csprogs.dat ../../.tmp/client.qc
++ basename ../../../../gmqcc/gmqcc
+ echo + gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../csprogs.dat ../../.tmp/client.qc
+ gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../csprogs.dat ../../.tmp/client.qc
+ cd tools
+ ../../../../gmqcc/gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../csprogs.dat ../../.tmp/client.qc
stat.cpp:31:19: runtime error: pointer index expression with base 0x000000000000 overflowed to 0xfffffffffffffff0
    #0 0x87bd41 in _util_vec_grow(void**, unsigned long, unsigned long) /home/matthias/vcs/git/xonotic/gmqcc/stat.cpp:31:19
    #1 0x765a9d in options_parse(int, char**) /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:484:13
    #2 0x75522b in main /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:532:10
    #3 0x7f4e8ceaa430 in __libc_start_main (/lib64/libc.so.6+0x20430)
    #4 0x41bef9 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x41bef9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior stat.cpp:31:19 in 
Mode: manual
There are 1 items to compile:
  item: ../../.tmp/client.qc (qc)
fold.cpp:1387:20: runtime error: downcast of misaligned address 0x000000000001 for type 'ast_value', which requires 8 byte alignment
0x000000000001: note: pointer points here
<memory cannot be printed>
    #0 0x5d3a44 in fold::op(oper_info const*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/fold.cpp:1387:20
    #1 0x7efd76 in parser_sy_apply_operator(parser_t*, shunt*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:902:40
    #2 0x7c6d48 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1959:14
    #3 0x82f6af in parse_while_go(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:2272:12
    #4 0x826cbb in parse_while(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:2239:10
    #5 0x81d620 in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3500:20
    #6 0x81a7a5 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3768:14
    #7 0x7d33ba in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:4157:10
    #8 0x7a09d7 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5731:18
    #9 0x78c6d1 in parser_global_statement(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5900:16
    #10 0x781cbd in parser_compile(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6108:18
    #11 0x781945 in parser_compile_file(parser_t*, char const*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6138:12
    #12 0x75b09b in main /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:709:26
    #13 0x7f4e8ceaa430 in __libc_start_main (/lib64/libc.so.6+0x20430)
    #14 0x41bef9 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x41bef9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior fold.cpp:1387:20 in 
fold.cpp:1386:20: runtime error: downcast of misaligned address 0x0000004a6b45 for type 'ast_value', which requires 8 byte alignment
0x0000004a6b45: note: pointer points here
 2b 50 7d 00 48 81 c4  38 08 00 00 5b 41 5c 41  5d 41 5e 41 5f 5d c3 4c  89 ff 4c 89 f6 4c 89 e2  48
             ^ 
    #0 0x5d3926 in fold::op(oper_info const*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/fold.cpp:1386:20
    #1 0x7dd4ba in parser_sy_apply_operator(parser_t*, shunt*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:511:40
    #2 0x7c6d48 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1959:14
    #3 0x82cc57 in parse_expression(parser_t*, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1984:25
    #4 0x822fec in parse_return(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:2662:15
    #5 0x81d17e in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3492:20
    #6 0x81a7a5 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3768:14
    #7 0x7d33ba in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:4157:10
    #8 0x7a09d7 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5731:18
    #9 0x78c6d1 in parser_global_statement(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5900:16
    #10 0x781cbd in parser_compile(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6108:18
    #11 0x781945 in parser_compile_file(parser_t*, char const*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6138:12
    #12 0x75b09b in main /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:709:26
    #13 0x7f4e8ceaa430 in __libc_start_main (/lib64/libc.so.6+0x20430)
    #14 0x41bef9 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x41bef9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior fold.cpp:1386:20 in 
+ err=0
+ set -e
+ '[' 0 -ne 0 ']'
+ sed 's/^#\(line\)\? \([[:digit:]]\+\) "\(.*\)".*/\n#pragma file(\3)\n#pragma line(\2)/g' ../.tmp/server.txt
+ qcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../progs.dat ../../.tmp/server.qc
++ basename ../../../../gmqcc/gmqcc
+ echo + gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../progs.dat ../../.tmp/server.qc
+ gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../progs.dat ../../.tmp/server.qc
+ cd tools
+ ../../../../gmqcc/gmqcc -std=gmqcc -Ooverlap-locals -O3 -Werror -Wall -Wno-field-redeclared -flno -futf8 -fno-bail-on-werror -frelaxed-switch -freturn-assignments -o /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../progs.dat ../../.tmp/server.qc
stat.cpp:31:19: runtime error: pointer index expression with base 0x000000000000 overflowed to 0xfffffffffffffff0
    #0 0x87bd41 in _util_vec_grow(void**, unsigned long, unsigned long) /home/matthias/vcs/git/xonotic/gmqcc/stat.cpp:31:19
    #1 0x765a9d in options_parse(int, char**) /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:484:13
    #2 0x75522b in main /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:532:10
    #3 0x7fe43f25a430 in __libc_start_main (/lib64/libc.so.6+0x20430)
    #4 0x41bef9 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x41bef9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior stat.cpp:31:19 in 
Mode: manual
There are 1 items to compile:
  item: ../../.tmp/server.qc (qc)
fold.cpp:1387:20: runtime error: downcast of misaligned address 0x000000000001 for type 'ast_value', which requires 8 byte alignment
0x000000000001: note: pointer points here
<memory cannot be printed>
    #0 0x5d3a44 in fold::op(oper_info const*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/fold.cpp:1387:20
    #1 0x7f18c9 in parser_sy_apply_operator(parser_t*, shunt*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:922:40
    #2 0x7c6d48 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1959:14
    #3 0x824645 in parse_if(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:2149:12
    #4 0x81d3cf in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3496:20
    #5 0x81a7a5 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3768:14
    #6 0x82ca68 in parse_block(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3800:10
    #7 0x82d35e in parse_statement_or_block(parser_t*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3810:16
    #8 0x82fcb8 in parse_while_go(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:2287:10
    #9 0x826cbb in parse_while(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:2239:10
    #10 0x81d620 in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3500:20
    #11 0x81a7a5 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3768:14
    #12 0x7d33ba in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:4157:10
    #13 0x7a09d7 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5731:18
    #14 0x78c6d1 in parser_global_statement(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5900:16
    #15 0x781cbd in parser_compile(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6108:18
    #16 0x781945 in parser_compile_file(parser_t*, char const*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6138:12
    #17 0x75b09b in main /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:709:26
    #18 0x7fe43f25a430 in __libc_start_main (/lib64/libc.so.6+0x20430)
    #19 0x41bef9 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x41bef9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior fold.cpp:1387:20 in 
fold.cpp:1386:20: runtime error: downcast of misaligned address 0x0000004a6b45 for type 'ast_value', which requires 8 byte alignment
0x0000004a6b45: note: pointer points here
 2b 50 7d 00 48 81 c4  38 08 00 00 5b 41 5c 41  5d 41 5e 41 5f 5d c3 4c  89 ff 4c 89 f6 4c 89 e2  48
             ^ 
    #0 0x5d3926 in fold::op(oper_info const*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/fold.cpp:1386:20
    #1 0x7dd4ba in parser_sy_apply_operator(parser_t*, shunt*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:511:40
    #2 0x7c6d48 in parse_expression_leave(parser_t*, bool, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1959:14
    #3 0x82cc57 in parse_expression(parser_t*, bool, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:1984:25
    #4 0x822fec in parse_return(parser_t*, ast_block*, ast_expression**) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:2662:15
    #5 0x81d17e in parse_statement(parser_t*, ast_block*, ast_expression**, bool) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3492:20
    #6 0x81a7a5 in parse_block_into(parser_t*, ast_block*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:3768:14
    #7 0x7d33ba in parse_function_body(parser_t*, ast_value*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:4157:10
    #8 0x7a09d7 in parse_variable(parser_t*, ast_block*, bool, int, ast_value*, bool, bool, unsigned int, char*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5731:18
    #9 0x78c6d1 in parser_global_statement(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:5900:16
    #10 0x781cbd in parser_compile(parser_t*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6108:18
    #11 0x781945 in parser_compile_file(parser_t*, char const*) /home/matthias/vcs/git/xonotic/gmqcc/parser.cpp:6138:12
    #12 0x75b09b in main /home/matthias/vcs/git/xonotic/gmqcc/main.cpp:709:26
    #13 0x7fe43f25a430 in __libc_start_main (/lib64/libc.so.6+0x20430)
    #14 0x41bef9 in _start (/home/matthias/vcs/git/xonotic/gmqcc/gmqcc+0x41bef9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior fold.cpp:1386:20 in 
writing '/home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.dat' and '/home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.lno'...

Optimizations:
    peephole: 4148
    overlap locals: 3166
    call stores: 9997
    void return: 1409
    const fold dce: 1181
    const fold: 783

File statistics:
    dat:
        name: /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.dat
        size: 1744474 (bytes)
        crc:  0x2724
    lno:
        name: /home/matthias/vcs/git/xonotic/data/xonotic-data.pk3dir/qcsrc/../menu.lno
        size: 1051112 (bytes)


=================================================================
````
gmqcc @ 3cf2c52fce792af3e5cc5578b336de83217e625d

**Comment by graphitemaster** [comment]
Pushed a fix for this

**Comment by matthiaskrgr** [comment]
Looks good.
